### ISSUE TITLE
(*Cert).Apply(...) crashes

### ISSUE THREAD

**Issue by jordansissel** [zeromq/goczmq#189] opened 2015-11-14 03:56 UTC
I noticed this tonight while trying to resurrect some old code and found its test suite fails when I call `cert.Apply(sock)`. Checking the goczmq test suite, it looks like the same thing fails (yay tests!)

I haven't yet dug into why this is failing.

```
# OSX 10.11
% brew info czmq zeromq libsodium | grep ', HEAD'
czmq: stable 3.0.2 (bottled), HEAD
zeromq: stable 4.1.3 (bottled), HEAD
libsodium: stable 1.0.6 (bottled), HEAD

% clang --version
Apple LLVM version 7.0.0 (clang-700.1.76)
Target: x86_64-apple-darwin15.0.0
Thread model: posix

% go version
go version go1.5.1 darwin/amd64
```

Test failure output
```
% go test .
Assertion failed: (rc == 0 || zmq_errno () == ETERM), function zsocket_set_curve_secretkey_bin, file src/zsockopt.c, line 482.
SIGABRT: abort
PC=0x7fff8f9320ae m=0
signal arrived during cgo execution

goroutine 7 [syscall, locked to thread]:
runtime.cgocall(0x4002630, 0xc82003bcc8, 0x0)
        /usr/local/Cellar/go/1.5.1/libexec/src/runtime/cgocall.go:120 +0x11b fp=0xc82003bc98 sp=0xc82003bc68
_/Users/jls/projects/goczmq._Cfunc_zsocket_set_curve_secretkey_bin(0x680a200, 0x5202660)
        _/Users/jls/projects/goczmq/_test/_obj_test/_cgo_gotypes.go:1852 +0x31 fp=0xc82003bcc8 sp=0xc82003bc98
_/Users/jls/projects/goczmq.(*Cert).Apply(0xc82002c0f8, 0xc820013a40)
        /Users/jls/projects/goczmq/cert.go:94 +0x57 fp=0xc82003bce8 sp=0xc82003bcc8
_/Users/jls/projects/goczmq.TestAuthCurveAllowAny(0xc82007c5a0)
        /Users/jls/projects/goczmq/auth_test.go:201 +0x244 fp=0xc82003bf68 sp=0xc82003bce8
testing.tRunner(0xc82007c5a0, 0x4314f50)
        /usr/local/Cellar/go/1.5.1/libexec/src/testing/testing.go:456 +0x98 fp=0xc82003bfa0 sp=0xc82003bf68
runtime.goexit()
        /usr/local/Cellar/go/1.5.1/libexec/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82003bfa8 sp=0xc82003bfa0
created by testing.RunTests
        /usr/local/Cellar/go/1.5.1/libexec/src/testing/testing.go:561 +0x86d
```

**Comment by jordansissel** [comment] 2015-11-14 04:14
I rebuilt libsodium and czmq from source, just to see if it was a weird binary problem, and that seems to have resolved it.

```
% brew reinstall --build-from-source libsodium

% go test .
# fails ...

% brew reinstall --build-from-source czmq
% go test .
# success!
```

**Comment by jordansissel** [comment] 2015-11-14 04:14
(I rebuilt the already-installed versions of libsodium and czmq with homebrew with no other changes and things are happy now; closing)

**Comment by jordansissel** [comment] 2015-11-14 04:17
(Deleted my prior comments where I thought I fixed this by reinstalling libsodium/czmq)

Reopening - I'm still not sure how to solve this. Will keep digging.

**Comment by taotetek** [comment] 2015-11-22 18:20
@jordansissel thanks for the issue!  I was crazy busy getting ready for the elasticsearch conference and missed this issue - I can see if I can reproduce it on linux - what version of libsodium / czmq are you on?

That test is currently passing locally for me. Looking at your output - is it possible that your underlying libzmq library is compiled without sodium enabled?   You can "configure --with-libsodium" when building libzmq to be explicit about it.

**Comment by taotetek** [comment] 2015-12-07 11:43
@jordansissel I'm going to close this as I'm unable to reproduce - but if it turns out to be not related to your environment or if you want help diagnosing it feel free to re-open!

**Closed by taotetek** 2015-12-07 11:43 UTC
Labels: question

**Comment by jordansissel** [comment] 2015-12-07 19:24
+1 on closing. I'm not sure what's going on. Will re-open if I hit it again :)
